Implement much more or RAFT

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -33,10 +33,13 @@ raft.top: $(ARCHIVE)
 run: raft.top
 	rlwrap ./raft.top -init raft.init
 
-check.byte: $(ARCHIVE)
-check.opt: $(XARCHIVE)
-check-spec: check.byte
-	@./check.byte || echo -e "======================\ncustom checks FAILED!!\n======================"
+TEST_PROGRAMS = check.ml raft_check.ml
+check.cmo: $(ARCHIVE)
+raft_check.cmo: $(ARCHIVE)
+check-spec: $(TEST_PROGRAMS:.ml=.byte)
+	@for p in $^ ; do \
+	  ./$$p && echo "$$p OK" || echo "\n     XXXXX $$p FAILED!! XXXXX\n" ;\
+	done
 
 clean-spec:
 
